project:
  type: book
  output-dir: docs

book:
  title: "STAT 9610 Lecture Notes"
  author: "Eugene Katsevich"
  downloads: pdf
  chapters:
    - index.qmd

    - part: linear-models-estimation.qmd
      chapters:
        - predictors-and-coefficients.qmd
        - linear-model-spaces.qmd
        - least-squares-estimation.qmd
        - anova.qmd
        - special-cases.qmd
        - collinearity.qmd
        - r-demo-part-1.qmd

    - part: linear-models-inference.qmd
      chapters:
        - building-blocks.qmd
        - hypothesis-testing.qmd
        - power.qmd
        - confidence-intervals.qmd
        - practical-considerations.qmd
        - r-demo-part-2.qmd

    - part: linear-models-misspecification.qmd
      chapters:
        - misspecification-overview.qmd
        - asymptotic-methods.qmd
        - bootstrap.qmd
        - permutation-test.qmd
        - robust-estimation.qmd
        - r-demo-part-3.qmd

    - part: glm-general-theory.qmd
      chapters:
        - exponential-dispersion-models.qmd
        - generalized-linear-models.qmd
        - parameter-estimation.qmd
        - glm-inference.qmd
        - r-demo-part-4.qmd

    - part: glm-special-cases.qmd
      chapters:
        - logistic-regression.qmd
        - poisson-regression.qmd
        - negative-binomial-regression.qmd
        - r-demo-part-5.qmd
    - part: multiple-testing.qmd
      chapters:
        - multiple-testing-intro.qmd
        - global-testing.qmd
        - multiple-testing-chapter.qmd
format:
  html:
    theme:
      - cosmo
      - custom.scss
    grid:
      body-width: 1000px
    mainfont: "Computer Modern"
    fig-align: center
  pdf:
    documentclass: book
    pdf-engine: pdflatex
    keep-tex: true
    toc-depth: 2
    classoption: "oneside"  # Set the oneside option directly in the document class
    fontsize: 11pt
    geometry: "left=1in,right=1in,top=1in,bottom=1in"  # Define margins here
    lang: "english"
    header-includes: |
      \usepackage{lmodern}
      \usepackage{bm, bbm}
      \usepackage{amsmath, amsfonts, amssymb, amsthm}
      \usepackage{fancyhdr}
      \pagestyle{fancy} % turns on fancy header styles
      \fancyhf{} % clear all header and footer fields
      \makeatletter
      \lhead{\@author} % left header
      \chead{\@title} % center header
      \makeatother
      \rhead{Page \thepage} % right header
      \setlength{\headheight}{13.6pt} % fixes minor warning
      \makeatother % change back interpretation of @


