project:
  type: book
  output-dir: docs

book:
  title: "STAT 9610<br>Lecture Notes"
  author: "Eugene Katsevich"
  downloads: pdf
  chapters:
    - index.qmd

    - part: linear-models-estimation.qmd
      chapters:
        - predictors-and-coefficients.qmd
        - linear-model-spaces.qmd
        - least-squares-estimation.qmd
        - anova.qmd
        - special-cases.qmd
        - collinearity.qmd
        - r-demo-part-1.qmd

    - linear-models-inference.qmd
    - linear-models-misspecification.qmd
    - glm-general-theory.qmd
    - glm-special-cases.qmd
    - multiple-testing.qmd
format:
  html:
    theme: cosmo
    css: custom.css
    mathjax:
      config: |
        MathJax.Hub.Config({
          TeX: {
            Macros: {
              mathbbm: ["{\\mathbb{#1}}",1]
            }
          }
        });
  pdf:
    documentclass: book
    pdf-engine: pdflatex
    keep-tex: true
    classoption: "oneside"  # Set the oneside option directly in the document class
    fontsize: 11pt
    geometry: "left=1in,right=1in,top=1in,bottom=1in"  # Define margins here
    lang: "english"
    header-includes: |
      \usepackage{lmodern}
      \usepackage{bm, bbm}
      \usepackage{amsmath, amsfonts, amssymb, amsthm}
      \usepackage{fancyhdr}
      \pagestyle{fancy} % turns on fancy header styles
      \fancyhf{} % clear all header and footer fields
      \makeatletter
      \lhead{\@author} % left header
      \chead{\@title} % center header
      \makeatother
      \rhead{Page \thepage} % right header
      \setlength{\headheight}{13.6pt} % fixes minor warning
      \makeatother % change back interpretation of @


